const IDEAS_AR = [
  {emoji:"🔥",genre:"Battle Royale",title:"تحديت صديقي في Fortnite بدون بناء!",description:"تحدي مثير بين صديقين في No Build Mode، مين أقوى؟",why:"المحتوى التنافسي مع الأصدقاء بيحصل على تفاعل عالي",reason:"الجمهور بيحب يشوف ردود أفعال حقيقية وتحديات بين أصحاب",successRate:92,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات التحدي بتوصل لملايين","No Build من أكتر الأوضاع شعبية"],challenges:["تحدي السلاح الواحد","تحدي بدون قفز","الفوز بأقل كيلز"]},
  {emoji:"😱",genre:"FPS",title:"أول مرة ألعب Valorant وعملت Ace!",description:"تجربة لاعب جديد عمل Ace في أول ماتش، ردود فعله مش متوقعة!",why:"محتوى المبتدئين اللي بيعملوا حاجات غير متوقعة بيفجر",reason:"الجمهور بيتفاعل مع المشاعر الحقيقية والمواقف العفوية",successRate:89,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات الـ Ace بتوصل لملايين في تيك توك","محتوى المبتدئين من أعلى محتوى في الجيمنج"],challenges:["Ace بعيون مغمضة","Ace بأضعف سلاح","Ace بدون أبيليتي"]},
  {emoji:"🎯",genre:"MOBA",title:"سر الـ Rank Up في Mobile Legends في أسبوع!",description:"استراتيجية سرية للوصول من Gold لـ Mythic في أسبوع واحد بس!",why:"محتوى الـ Rank Up من أكتر المحتوى اللي الناس بتدور عليه",reason:"كل لاعب عايز يرفع رانك وبيدور على طرق سريعة",successRate:88,successLabel:"نار 🔥",successType:"hot",proof:["سيرش Rank Up بيجيب ملايين النتايج","محتوى الجايد دايماً في التريند"],challenges:["Rank Up بهيرو واحد","Rank Up في أقل وقت","Rank Up بدون ما تموت"]},
  {emoji:"🏆",genre:"Battle Royale",title:"فزت بـ PUBG بدون ما أطلق رصاصة!",description:"تحدي مجنون الفوز بالدوري بدون إطلاق أي رصاصة بالاختباء والتحرك الذكي!",why:"التحديات المستحيلة بتجيب مشاهدات ضخمة",reason:"الناس فضولية تعرف هل ممكن تفوز بدون قتال",successRate:94,successLabel:"نار 🔥",successType:"hot",proof:["تحديات PUBG الغريبة بتوصل لـ 10 مليون","محتوى الـ Challenge من أعلى محتوى"],challenges:["فوز بدون سلاح","فوز بالعدو بس","فوز بدون ما تتحرك"]},
  {emoji:"⚡",genre:"FPS",title:"أقوى 5 إعدادات تخليك Predator في Warzone!",description:"شرح تفصيلي لأفضل الإعدادات في Warzone تزيد الـ FPS وتحسن الأداء!",why:"محتوى الإعدادات والتيبس من أعلى محتوى سيرشاً",reason:"كل لاعب عايز يحسن أداءه وبيدور على إعدادات الـ Pro",successRate:87,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات الإعدادات بتوصل لـ 5 مليون","من أكتر الكلمات سيرشاً في جيمنج يوتيوب"],challenges:["أفضل إعدادات موبايل","إعدادات اللاعبين المحترفين","إعدادات للأجهزة الضعيفة"]},
  {emoji:"😂",genre:"Mobile",title:"لما أمي لعبت Clash of Clans بدلي!",description:"تجربة مضحكة لما الأم لعبت بدل ابنها والنتايج كانت كارثية وممتعة!",why:"محتوى العيلة والأهل مع الجيمنج بيفجر دايماً",reason:"الجمهور بيحب يتفاعل مع المواقف العيلية المضحكة",successRate:91,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات الأهل مع الجيمنج من أعلى المحتوى","تفاعل ضخم على السوشيال ميديا"],challenges:["أمي تلعب Fortnite","أبويا يحاول يفهم Valorant","أخويا الصغير يلعب بدلي"]},
  {emoji:"💀",genre:"Horror",title:"لعبت Five Nights at Freddy's لأول مرة وجننت!",description:"رد فعل حقيقي وعفوي على أول تجربة في FNAF، الخوف والضحك مع بعض!",why:"فيديوهات الخوف والـ Reaction من أعلى محتوى",reason:"الجمهور بيحب يشوف ردود الفعل الحقيقية على ألعاب الرعب",successRate:90,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات الـ Reaction على FNAF بتوصل لملايين","ألعاب الرعب من أعلى المحتوى تفاعلاً"],challenges:["لعب من غير صوت","لعب بعيون نص مفتوحة","تحدي اللعب لساعة كاملة"]},
  {emoji:"🚀",genre:"Battle Royale",title:"استراتيجية الـ Solo vs Squad وأنا كسبت!",description:"تحدي Solo vs Squad في Warzone وتحقيق الفوز ضد فريق كامل من 4 أشخاص!",why:"Solo vs Squad من أكتر التحديات اللي الناس بتتفرج عليها",reason:"الإحساس بالإنجاز والتحدي بيخلي الناس تتفاعل وتشارك",successRate:93,successLabel:"نار 🔥",successType:"hot",proof:["Solo vs Squad محتوى دايم في التريند","من أعلى كلمات السيرش في Warzone"],challenges:["Solo vs Squad بسلاح واحد","Solo vs Squad بدون scope","فوز على 3 أفرقة متتالية"]},
  {emoji:"🏅",genre:"FPS",title:"من Unranked لـ Diamond في Valorant في شهر!",description:"رحلة كاملة من البداية لـ Diamond في Valorant خلال شهر واحد مع شرح كل خطوة.",why:"رحلات الـ Rank Up من أعلى محتوى متابعة",reason:"الناس بتحب تتابع الرحلات الطويلة وتتعلم منها",successRate:87,successLabel:"نار 🔥",successType:"hot",proof:["سلاسل Rank Up Journey من أعلى سلاسل يوتيوب","التفاعل على الـ Progress Videos ضخم"],challenges:["Rank Up بـ Agent واحد بس","Rank Up خلال أسبوعين","Rank Up من Iron لـ Radiant"]},
  {emoji:"🌟",genre:"Mobile",title:"Free Fire vs PUBG Mobile مين أحسن في 2025؟",description:"مقارنة شاملة وصريحة بين Free Fire و PUBG Mobile من ناحية الجرافيكس والجيمبلاي.",why:"فيديوهات المقارنة بين الألعاب من أعلى محتوى",reason:"كل لاعب عنده رأي وبيحب يشارك ويتجادل",successRate:88,successLabel:"نار 🔥",successType:"hot",proof:["فيديوهات المقارنة بتجيب تفاعل ضخم في التعليقات","من أعلى المحتوى الموبايل سيرشاً"],challenges:["مقارنة الـ Graphics","مقارنة الـ Gameplay","مقارنة المجتمع"]},
  {emoji:"⚔️",genre:"MOBA",title:"أفضل 3 هيروز في Arena of Valor للمبتدئين!",description:"شرح مبسط لأفضل 3 هيروز سهلة وقوية للمبتدئين في Arena of Valor.",why:"محتوى الـ Guide للمبتدئين دايماً في الطلب",reason:"في ملايين لاعب جديد بيدخل الألعاب كل يوم",successRate:83,successLabel:"جيد ✅",successType:"good",proof:["Arena of Valor من أكتر الألعاب المنتشرة في الشرق الأوسط","محتوى المبتدئين من أعلى محتوى يوتيوب"],challenges:["Guide للدعم","Guide للـ Jungle","Guide للـ Tank"]},
  {emoji:"🎮",genre:"General",title:"إزاي تبدأ قناة جيمنج ناجحة في 2025!",description:"دليل عملي شامل لبدء قناة جيمنج ناجحة في 2025 من الصفر.",why:"محتوى كيف تبدأ قناة يوتيوب من أعلى محتوى بحثاً",reason:"ملايين شاب بيحلم ببدء قناة جيمنج ناجحة",successRate:92,successLabel:"نار 🔥",successType:"hot",proof:["How to Start Gaming Channel من أعلى كلمات البحث","المحتوى ده بيجيب مشتركين جدد كتير"],challenges:["بدء قناة بدون معدات","أول 1000 مشترك","المونتاج المحترف مجاناً"]},
  {emoji:"💰",genre:"General",title:"كيف تكسب من الجيمنج في مصر والسعودية 2025!",description:"شرح عملي وواقعي لطرق الكسب من الجيمنج في العالم العربي.",why:"محتوى الكسب من الجيمنج من أعلى محتوى بحثاً",reason:"كل شاب في العالم العربي بيحلم يكسب من الجيمنج",successRate:93,successLabel:"نار 🔥",successType:"hot",proof:["من أكتر الكلمات بحثاً في الجيمنج العربي","التفاعل على المحتوى ده ضخم جداً"],challenges:["Streaming على تويتش","Esports المحترف","يوتيوب والمونتاج"]},
  {emoji:"😤",genre:"Battle Royale",title:"تحديت نفسي بـ 100 Win في أسبوع!",description:"تحدي تحقيق 100 Win في PUBG Mobile خلال أسبوع واحد كامل!",why:"100 Win Challenge من أعلى تحديات الجيمنج",reason:"التحديات الصعبة بتجيب متابعة مستمرة وتفاعل ضخم",successRate:91,successLabel:"نار 🔥",successType:"hot",proof:["100 Win Challenge فيروسي في جيمنج يوتيوب","التحديات الطموحة بتبني قاعدة جماهيرية قوية"],challenges:["100 Kill في يوم","Win 50 مرة متتالية","1000 ساعة جيمنج"]},
  {emoji:"🎭",genre:"General",title:"تحديت أفضل لاعب في المنطقة!",description:"قبول تحدي من أفضل لاعب في المنطقة، التحضير والمباراة والنتيجة الصادمة!",why:"Player vs Player Challenges من أعلى محتوى",reason:"الجمهور بيحب يشوف المنافسات الحقيقية والدراما",successRate:92,successLabel:"نار 🔥",successType:"hot",proof:["1v1 Challenge من أعلى محتوى تفاعلاً","التحديات الشخصية بتجيب دراما وتفاعل ضخم"],challenges:["تحدي أفضل لاعب في مصر","تحدي Pro Player","تحدي المشترك الـ 10000"]},
  {emoji:"🌙",genre:"RPG",title:"لعبت 24 ساعة متواصلة في Elden Ring!",description:"تحدي 24 ساعة في Elden Ring بدون نوم، التحديات والمشاعر الحقيقية!",why:"تحديات الـ Marathon Gaming من أعلى محتوى متابعة",reason:"الجمهور بيتابع التحديات الطويلة ويشجع ويتفاعل",successRate:91,successLabel:"نار 🔥",successType:"hot",proof:["24 Hour Gaming Challenge من أعلى تحديات يوتيوب","التفاعل على الـ Streams الطويلة ضخم"],challenges:["24 ساعة في Dark Souls","48 ساعة في Minecraft","لعب بدون نوم لأسبوع"]},
  {emoji:"🔫",genre:"FPS",title:"أفضل Loadout في Warzone بعد التحديث الجديد!",description:"شرح أفضل Loadout في Warzone بعد آخر تحديث مع مقارنة الأسلحة.",why:"Best Loadout After Update من أعلى كلمات البحث",reason:"كل تحديث بيغير المحتوى وكل لاعب بيدور على أفضل Loadout",successRate:90,successLabel:"نار 🔥",successType:"hot",proof:["Warzone Best Loadout من أعلى كلمات البحث دايماً","المحتوى بعد التحديثات بيجيب مشاهدات ضخمة فوراً"],challenges:["Loadout بعد كل Nerf","أرخص Loadout فعال","Loadout المحترفين"]},
  {emoji:"💪",genre:"FPS",title:"تدريب الـ Aim لمدة 30 يوم والنتيجة!",description:"تجربة تدريب منظم على الـ Aim لمدة 30 يوم ورؤية التحسن الحقيقي.",why:"Aim Training Challenge من أعلى محتوى FPS",reason:"كل لاعب FPS عايز يحسن Aim وبيتابع التجارب دي",successRate:89,successLabel:"نار 🔥",successType:"hot",proof:["30 Day Aim Training من أعلى تحديات الجيمنج","قبل وبعد التدريب بيجيب تفاعل ضخم"],challenges:["60 يوم Aim Training","Aim Training مع Pro Coach","من أسوأ Aim لـ Radiant"]},
  {emoji:"😂",genre:"FPS",title:"لعبت Valorant بعيون مغمضة وده اللي حصل!",description:"تحدي مضحك لعب Valorant بعيون مغمضة بالكامل، والنتيجة كانت مجنونة!",why:"Blind Gaming Challenge من أعلى تحديات الكوميديا",reason:"التحديات المستحيلة الكوميدية بتجيب ضحك وتفاعل ضخم",successRate:89,successLabel:"نار 🔥",successType:"hot",proof:["Blind Gaming Challenge فيروسي جداً","الجمهور بيحب التحديات المضحكة والمستحيلة"],challenges:["PUBG بعيون مغمضة","FIFA بعيون مغمضة","Racing Games بعيون مغمضة"]},
  {emoji:"🎯",genre:"Mobile",title:"أفضل Settings للـ Sensitivity في PUBG Mobile!",description:"شرح تفصيلي لأفضل إعدادات الـ Sensitivity في PUBG Mobile لكل أنواع اللعب.",why:"Best Sensitivity PUBG Mobile من أعلى كلمات البحث",reason:"كل لاعب PUBG Mobile بيدور على الـ Sensitivity المثالية",successRate:87,successLabel:"نار 🔥",successType:"hot",proof:["PUBG Mobile Sensitivity Guide من أعلى محتوى","من أكتر الأسئلة في مجتمع PUBG Mobile"],challenges:["Sensitivity للـ Gyroscope","Sensitivity على جهاز ضعيف","Sensitivity المحترفين"]}
];

const IDEAS_EN = [
  {emoji:"🔥",genre:"Battle Royale",title:"I Challenged My Friend in Fortnite No Build!",description:"An epic challenge between two friends in No Build Mode, who's stronger without building?",why:"Competitive content with friends gets massive engagement",reason:"Audiences love seeing real reactions and friend challenges",successRate:92,successLabel:"Fire 🔥",successType:"hot",proof:["Friend challenge videos reach millions of views","No Build Mode is one of the most popular Fortnite modes"],challenges:["One weapon only challenge","No jumping challenge","Win with minimum kills"]},
  {emoji:"😱",genre:"FPS",title:"First Time Playing Valorant and Got an Ace!",description:"A new player's experience in Valorant accidentally getting an Ace in their first match!",why:"Content of beginners doing unexpected things explodes",reason:"Audiences engage with real emotions and spontaneous moments",successRate:89,successLabel:"Fire 🔥",successType:"hot",proof:["Ace videos reach millions on TikTok","Beginner content is top gaming content"],challenges:["Ace with eyes closed","Ace with weakest weapon","Ace without abilities"]},
  {emoji:"🎯",genre:"MOBA",title:"Secret to Rank Up in Mobile Legends in One Week!",description:"A secret strategy to go from Gold to Mythic in just one week with the strongest heroes!",why:"Rank Up content is one of the most searched gaming content",reason:"Every player wants to rank up and looks for fast methods",successRate:88,successLabel:"Fire 🔥",successType:"hot",proof:["Rank Up search returns millions of results","Guide content is always trending"],challenges:["Rank up with one hero","Rank up in minimum time","Rank up without dying"]},
  {emoji:"🏆",genre:"Battle Royale",title:"Won PUBG Without Firing a Single Shot!",description:"A crazy challenge to win in PUBG without shooting anyone, using only stealth and smart movement!",why:"Impossible challenges get massive views",reason:"People are curious if you can win without fighting",successRate:94,successLabel:"Fire 🔥",successType:"hot",proof:["Weird PUBG challenges reach 10 million views","Challenge content is top performing"],challenges:["Win without weapons","Win using only the zone","Win without moving"]},
  {emoji:"⚡",genre:"FPS",title:"Top 5 Settings That Make You a Predator in Warzone!",description:"Detailed breakdown of the best Warzone settings to boost FPS and improve performance!",why:"Settings and tips content is among the most searched",reason:"Every player wants to improve and looks for pro settings",successRate:87,successLabel:"Fire 🔥",successType:"hot",proof:["Settings videos reach 5 million views","One of the most searched terms in gaming YouTube"],challenges:["Best mobile settings","Pro player settings","Settings for low-end PCs"]},
  {emoji:"😂",genre:"Mobile",title:"My Mom Played Clash of Clans Instead of Me!",description:"A hilarious experience of a mom playing instead of her son, with disastrous and entertaining results!",why:"Family and parent gaming content always explodes",reason:"Audiences love funny family moments",successRate:91,successLabel:"Fire 🔥",successType:"hot",proof:["Parent gaming videos are top content","Huge engagement on social media"],challenges:["Mom plays Fortnite","Dad tries to understand Valorant","Little brother plays instead"]},
  {emoji:"💀",genre:"Horror",title:"Played Five Nights at Freddy's for the First Time!",description:"A genuine first-time reaction to FNAF, with real fear and laughter combined!",why:"Horror reaction videos are top-performing content",reason:"Audiences love watching genuine reactions to horror games",successRate:90,successLabel:"Fire 🔥",successType:"hot",proof:["FNAF reaction videos reach millions","Horror games have highest engagement content"],challenges:["Play without sound","Play with half-closed eyes","One hour straight challenge"]},
  {emoji:"🚀",genre:"Battle Royale",title:"Solo vs Squad Strategy and I Won!",description:"Solo vs Squad challenge in Warzone, winning against a full team of 4 players!",why:"Solo vs Squad is the most watched challenge type",reason:"The sense of achievement makes people engage and share",successRate:93,successLabel:"Fire 🔥",successType:"hot",proof:["Solo vs Squad content is always trending","Top searched terms in Warzone"],challenges:["Solo vs Squad with one weapon","Solo vs Squad without scope","Win against 3 squads in a row"]},
  {emoji:"🏅",genre:"FPS",title:"Unranked to Diamond in Valorant in One Month!",description:"A complete journey from the beginning to Diamond in Valorant in one month with every step explained.",why:"Rank Up journeys are top-viewed content",reason:"People love following long journeys and learning from them",successRate:87,successLabel:"Fire 🔥",successType:"hot",proof:["Rank Up Journey series are top YouTube series","Engagement on Progress Videos is massive"],challenges:["Rank up with one agent only","Rank up in two weeks","Rank up from Iron to Radiant"]},
  {emoji:"🌟",genre:"Mobile",title:"Free Fire vs PUBG Mobile - Which is Better in 2025?",description:"A comprehensive honest comparison between Free Fire and PUBG Mobile in terms of graphics and gameplay.",why:"Game comparison videos are top content",reason:"Every player has an opinion and loves to argue",successRate:88,successLabel:"Fire 🔥",successType:"hot",proof:["Comparison videos get massive comment engagement","Top mobile gaming search content"],challenges:["Graphics comparison","Gameplay comparison","Community comparison"]},
  {emoji:"⚔️",genre:"MOBA",title:"Best 3 Heroes in Arena of Valor for Beginners!",description:"Simple breakdown of the best easy and powerful heroes for beginners in Arena of Valor.",why:"Beginner guide content is always in demand",reason:"Millions of new players join games every day",successRate:83,successLabel:"Good ✅",successType:"good",proof:["Arena of Valor is one of the most popular games in Middle East","Beginner content is top YouTube gaming content"],challenges:["Support guide","Jungle guide","Tank guide"]},
  {emoji:"🎮",genre:"General",title:"How to Start a Successful Gaming Channel in 2025!",description:"A comprehensive practical guide to starting a successful gaming channel from scratch in 2025.",why:"How to start a YouTube channel is top searched content",reason:"Millions of young people dream of starting a successful gaming channel",successRate:92,successLabel:"Fire 🔥",successType:"hot",proof:["How to Start Gaming Channel is top search term","This content brings lots of new subscribers"],challenges:["Starting without equipment","First 1000 subscribers","Professional editing for free"]},
  {emoji:"💰",genre:"General",title:"How to Make Money from Gaming in 2025!",description:"A practical and realistic guide to making money from gaming worldwide.",why:"Gaming income content is top searched",reason:"Every young gamer dreams of making money from gaming",successRate:93,successLabel:"Fire 🔥",successType:"hot",proof:["One of the most searched terms in gaming","Engagement on this content is massive"],challenges:["Streaming on Twitch","Professional Esports","YouTube and editing"]},
  {emoji:"😤",genre:"Battle Royale",title:"I Challenged Myself to Get 100 Wins in a Week!",description:"The challenge of achieving 100 wins in PUBG Mobile in one full week!",why:"100 Win Challenge is top gaming challenge",reason:"Hard challenges bring continuous viewership and massive engagement",successRate:91,successLabel:"Fire 🔥",successType:"hot",proof:["100 Win Challenge goes viral in gaming YouTube","Ambitious challenges build strong audience base"],challenges:["100 kills in one day","Win 50 times in a row","1000 hours of gaming"]},
  {emoji:"🎭",genre:"General",title:"I Challenged the Best Player in the Region!",description:"Accepting a challenge from the best player in the region, the preparation, match and shocking result!",why:"Player vs Player Challenges are top content",reason:"Audiences love watching real competitions and drama",successRate:92,successLabel:"Fire 🔥",successType:"hot",proof:["1v1 Challenge is top engagement content","Personal challenges bring drama and massive interaction"],challenges:["Challenge the best player in Egypt","Challenge a Pro Player","Challenge subscriber number 10000"]},
  {emoji:"🌙",genre:"RPG",title:"I Played Elden Ring for 24 Hours Straight!",description:"A 24-hour Elden Ring challenge without sleep, with real challenges and emotions!",why:"Marathon Gaming challenges are top followed content",reason:"Audiences follow long challenges and cheer and interact",successRate:91,successLabel:"Fire 🔥",successType:"hot",proof:["24 Hour Gaming Challenge is top YouTube challenge","Engagement on long streams is massive"],challenges:["24 hours in Dark Souls","48 hours in Minecraft","Gaming without sleep for a week"]},
  {emoji:"🔫",genre:"FPS",title:"Best Loadout in Warzone After the New Update!",description:"Breakdown of the best Warzone loadout after the latest update with weapon comparisons.",why:"Best Loadout After Update is top search term",reason:"Every update changes the meta and every player looks for the best loadout",successRate:90,successLabel:"Fire 🔥",successType:"hot",proof:["Warzone Best Loadout is always a top search term","Post-update content gets massive immediate views"],challenges:["Loadout after every nerf","Cheapest effective loadout","Pro player loadouts"]},
  {emoji:"💪",genre:"FPS",title:"30 Days of Aim Training - The Results!",description:"An organized aim training experience for 30 days to see real and tangible improvement.",why:"Aim Training Challenge is top FPS content",reason:"Every FPS player wants to improve their aim and follows these experiments",successRate:89,successLabel:"Fire 🔥",successType:"hot",proof:["30 Day Aim Training is top gaming challenge","Before and after training gets massive engagement"],challenges:["60 days aim training","Aim training with pro coach","Worst aim to Radiant"]},
  {emoji:"😂",genre:"FPS",title:"I Played Valorant Blindfolded and This Happened!",description:"A funny challenge playing Valorant with completely closed eyes, the result was insane!",why:"Blind Gaming Challenge is top comedy challenge",reason:"Impossible comedy challenges bring laughs and massive engagement",successRate:89,successLabel:"Fire 🔥",successType:"hot",proof:["Blind Gaming Challenge goes very viral","Audiences love funny and impossible challenges"],challenges:["PUBG blindfolded","FIFA blindfolded","Racing games blindfolded"]},
  {emoji:"🎯",genre:"Mobile",title:"Best Sensitivity Settings in PUBG Mobile!",description:"Detailed explanation of the best sensitivity settings in PUBG Mobile for all play styles.",why:"Best Sensitivity PUBG Mobile is top search term",reason:"Every PUBG Mobile player looks for the perfect sensitivity",successRate:87,successLabel:"Fire 🔥",successType:"hot",proof:["PUBG Mobile Sensitivity Guide is top content","One of the most asked questions in PUBG Mobile community"],challenges:["Gyroscope sensitivity","Sensitivity for low-end device","Pro player sensitivity"]}
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  var lang = req.body.lang || 'ar';
  var genre = req.body.genre || '';
  var IDEAS = lang === 'en' ? IDEAS_EN : IDEAS_AR;

  var filtered = IDEAS.slice();
  if (genre) {
    var genreMap = { fps:'FPS', moba:'MOBA', 'battle royale':'Battle Royale', rpg:'RPG', mobile:'Mobile' };
    var mapped = genreMap[genre.toLowerCase()];
    if (mapped) {
      var g = filtered.filter(function(i) { return i.genre === mapped || i.genre === 'General'; });
      if (g.length >= 3) filtered = g;
    }
  }

  filtered.sort(function() { return Math.random() - 0.5; });
  return res.status(200).json({ ideas: filtered.slice(0, 3) });
}
