const IDEAS = [
  { emoji: "🔥", genre: "Battle Royale", title: "تحديت صديقي في Fortnite بدون بناء!", description: "تحدي مثير بين صديقين في وضع No Build، مين أقوى بدون بناء؟ ممكن تضيف رهانات مضحكة تزيد التشويق.", why: "المحتوى التنافسي مع الأصدقاء بيحصل على تفاعل عالي جداً", reason: "الجمهور بيحب يشوف ردود أفعال حقيقية وتحديات بين أصحاب", successRate: 92, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات التحدي بين الأصحاب بتوصل لملايين المشاهدات", "No Build Mode من أكتر الأوضاع شعبية في Fortnite"], challenges: ["تحدي السلاح الواحد بس", "تحدي بدون قفز", "تحدي الفوز بأقل كيلز"] },
  { emoji: "😱", genre: "FPS", title: "أول مرة ألعب Valorant وعملت Ace!", description: "تجربة لاعب جديد في Valorant وبالصدفة عمل Ace في أول ماتش، ردود فعله الحقيقية مش متوقعة!", why: "محتوى المبتدئين اللي بيعملوا حاجات غير متوقعة بيفجر", reason: "الجمهور بيتفاعل مع المشاعر الحقيقية والمواقف العفوية", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات الـ Ace بتوصل لملايين في تيك توك", "محتوى المبتدئين من أعلى محتوى في الجيمنج"], challenges: ["Ace بعيون مغمضة", "Ace بأضعف سلاح", "Ace من غير أبيليتي"] },
  { emoji: "🎯", genre: "MOBA", title: "سر الـ Rank Up في Mobile Legends في أسبوع!", description: "شرح استراتيجية سرية للوصول من Gold لـ Mythic في أسبوع واحد بس، مع تحليل لأقوى الهيروز الحالية.", why: "محتوى الـ Rank Up من أكتر المحتوى اللي الناس بتدور عليه", reason: "كل لاعب عايز يرفع رانك وبيدور على طرق سريعة", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["سيرش Rank Up في يوتيوب بيجيب ملايين النتايج", "محتوى الجايد دايماً في التريند"], challenges: ["Rank Up بهيرو واحد بس", "Rank Up في أقل وقت ممكن", "Rank Up بدون ما تموت"] },
  { emoji: "🏆", genre: "Battle Royale", title: "فزت بـ PUBG بدون ما أطلق رصاصة واحدة!", description: "تحدي مجنون في PUBG الفوز بالدوري بدون إطلاق أي رصاصة، بالاختباء والتحرك الذكي بس!", why: "التحديات المستحيلة بتجيب مشاهدات ضخمة", reason: "الناس فضولية تعرف هل ممكن تفوز بدون قتال", successRate: 94, successLabel: "نار 🔥", successType: "hot", proof: ["تحديات PUBG الغريبة بتوصل لـ 10 مليون مشاهدة", "محتوى الـ Challenge من أعلى محتوى"], challenges: ["فوز بدون سلاح", "فوز بالعدو بس", "فوز من غير ما تتحرك"] },
  { emoji: "⚡", genre: "FPS", title: "أقوى 5 إعدادات تخليك Predator في Warzone!", description: "شرح تفصيلي لأفضل الإعدادات في Warzone تزيد الـ FPS وتحسن الأداء، مجربة ومضمونة!", why: "محتوى الإعدادات والتيبس من أعلى محتوى سيرشاً", reason: "كل لاعب عايز يحسن أداءه وبيدور على إعدادات الـ Pro", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات الإعدادات بتوصل لـ 5 مليون مشاهدة", "من أكتر الكلمات سيرشاً في جيمنج يوتيوب"], challenges: ["أفضل إعدادات موبايل", "إعدادات اللاعبين المحترفين", "إعدادات للأجهزة الضعيفة"] },
  { emoji: "😂", genre: "Mobile", title: "لما أمي لعبت Clash of Clans بدلي!", description: "تجربة مضحكة لما الأم لعبت بدل ابنها في Clash of Clans والنتايج كانت كارثية وممتعة!", why: "محتوى العيلة والأهل مع الجيمنج بيفجر دايماً", reason: "الجمهور بيحب يتفاعل مع المواقف العيلية المضحكة", successRate: 91, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات الأهل مع الجيمنج من أعلى المحتوى", "تفاعل ضخم على السوشيال ميديا"], challenges: ["أمي تلعب Fortnite", "أبويا يحاول يفهم Valorant", "أخويا الصغير يلعب بدلي"] },
  { emoji: "🎮", genre: "RPG", title: "أسرار Genshin Impact مش حد عارفها في 2025!", description: "كشف 10 أسرار وأماكن مخفية في Genshin Impact مش موجودة في أي فيديو تاني، اكتشافات حصرية!", why: "محتوى الأسرار والـ Easter Eggs دايماً في التريند", reason: "مجتمع Genshin ضخم جداً وبيتفاعل مع أي محتوى جديد", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Genshin Impact من أعلى الألعاب سيرشاً على يوتيوب", "مجتمع Genshin من أكبر مجتمعات الجيمنج"], challenges: ["أسرار الخريطة الجديدة", "أماكن مخفية مش في الماب", "باجز مضحكة في اللعبة"] },
  { emoji: "💀", genre: "Horror", title: "لعبت Five Nights at Freddy's لأول مرة وجننت!", description: "رد فعل حقيقي وعفوي على أول تجربة في FNAF، الخوف والضحك مع بعض في فيديو ممتع!", why: "فيديوهات الخوف والـ Reaction من أعلى محتوى", reason: "الجمهور بيحب يشوف ردود الفعل الحقيقية على ألعاب الرعب", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات الـ Reaction على FNAF بتوصل لملايين", "ألعاب الرعب من أعلى المحتوى تفاعلاً"], challenges: ["لعب من غير صوت", "لعب بعيون نص مفتوحة", "تحدي اللعب لساعة كاملة"] },
  { emoji: "🚀", genre: "Battle Royale", title: "استراتيجية الـ Solo vs Squad وأنا كسبت!", description: "تحدي Solo vs Squad في Warzone وتحقيق الفوز ضد فريق كامل من 4 أشخاص، مع شرح الاستراتيجية!", why: "Solo vs Squad من أكتر التحديات اللي الناس بتتفرج عليها", reason: "الإحساس بالإنجاز والتحدي بيخلي الناس تتفاعل وتشارك", successRate: 93, successLabel: "نار 🔥", successType: "hot", proof: ["Solo vs Squad محتوى دايم في التريند", "من أعلى كلمات السيرش في Warzone"], challenges: ["Solo vs Squad بسلاح واحد", "Solo vs Squad بدون scope", "فوز على 3 أفرقة متتالية"] },
  { emoji: "🎯", genre: "FPS", title: "تحليل أخطاء المبتدئين في CS2 وإزاي تتجنبها!", description: "شرح أكبر 7 أخطاء بيعملها المبتدئين في CS2 وإزاي تتجنبها عشان ترفع رانكك بسرعة.", why: "محتوى التحسين والتعلم من أعلى المحتوى المطلوب", reason: "كل لاعب بيدور على طريقة يتحسن بيها في أسرع وقت", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["CS2 من أكتر الألعاب سيرشاً", "محتوى الـ Tips من أعلى محتوى تعليمي"], challenges: ["أخطاء في الـ Aim", "أخطاء في الـ Economy", "أخطاء في الـ Communication"] },
  { emoji: "🌟", genre: "Mobile", title: "Free Fire vs PUBG Mobile مين أحسن في 2025؟", description: "مقارنة شاملة وصريحة بين Free Fire و PUBG Mobile من ناحية الجرافيكس والجيمبلاي والمجتمع.", why: "فيديوهات المقارنة بين الألعاب من أعلى محتوى", reason: "كل لاعب عنده رأي وبيحب يشارك ويتجادل", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات المقارنة بتجيب تفاعل ضخم في التعليقات", "من أعلى المحتوى الموبايل سيرشاً"], challenges: ["مقارنة الـ Graphics", "مقارنة الـ Gameplay", "مقارنة المجتمع"] },
  { emoji: "⚔️", genre: "MOBA", title: "أفضل 3 هيروز في Arena of Valor للمبتدئين!", description: "شرح مبسط لأفضل 3 هيروز سهلة وقوية للمبتدئين في Arena of Valor مع نصايح عملية.", why: "محتوى الـ Guide للمبتدئين دايماً في الطلب", reason: "في ملايين لاعب جديد بيدخل الألعاب كل يوم", successRate: 83, successLabel: "جيد ✅", successType: "good", proof: ["Arena of Valor من أكتر الألعاب المنتشرة في الشرق الأوسط", "محتوى المبتدئين من أعلى محتوى يوتيوب"], challenges: ["Guide للدعم", "Guide للـ Jungle", "Guide للـ Tank"] },
  { emoji: "🔫", genre: "FPS", title: "أنا والـ AI تحدينا في Aim والنتيجة صدمتني!", description: "تحدي مثير بين اللاعب وبوت AI متقدم في الـ Aim، مين أفضل، الإنسان أم الذكاء الاصطناعي؟", why: "محتوى الذكاء الاصطناعي والجيمنج في القمة دلوقتي", reason: "موضوع الـ AI في الجيمنج من أكتر المواضيع تريندينج", successRate: 91, successLabel: "نار 🔥", successType: "hot", proof: ["موضوع AI vs Human من أعلى المحتوى", "الجمهور فضولي جداً للمقارنة دي"], challenges: ["AI vs Human في Valorant", "AI vs Human في CS2", "AI vs Human في Fortnite"] },
  { emoji: "😤", genre: "Battle Royale", title: "ردود فعلي لما فريقي خذلني في PUBG!", description: "فيديو كوميدي عن أصعب المواقف لما الفريق بيخذل ومع ذلك بيحاول يكمل ويفوز!", why: "محتوى الـ Rage والكوميديا من أعلى محتوى تفاعلاً", reason: "كل لاعب عنده تجارب مشابهة وبيتعاطف ويضحك", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["فيديوهات الـ Rage Gaming من أعلى محتوى", "التعليقات على المحتوى ده دايماً ضخمة"], challenges: ["لعب مع فريق أضعف مني", "لعب مع ناس مش بيتكلموا", "لعب بعد 3 ساعات من الخسارة"] },
  { emoji: "🏅", genre: "FPS", title: "من Unranked لـ Diamond في Valorant خلال شهر!", description: "رحلة كاملة من البداية لـ Diamond في Valorant خلال شهر واحد مع شرح كل خطوة وكل درس.", why: "رحلات الـ Rank Up من أعلى محتوى متابعة", reason: "الناس بتحب تتابع الرحلات الطويلة وتتعلم منها", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["سلاسل Rank Up Journey من أعلى سلاسل يوتيوب", "التفاعل على الـ Progress Videos ضخم"], challenges: ["Rank Up بـ Agent واحد بس", "Rank Up خلال أسبوعين", "Rank Up من Iron لـ Radiant"] },
  { emoji: "🎪", genre: "Mobile", title: "أغرب 5 باجز في Clash Royale مش حد شافها!", description: "كشف أغرب الباجز والأخطاء في Clash Royale اللي ممكن تستغلها أو تخليك تضحك!", why: "محتوى الباجز والـ Glitches دايماً فيروسي", reason: "الجمهور بيحب يشوف الأشياء الغريبة والغير متوقعة", successRate: 84, successLabel: "جيد ✅", successType: "good", proof: ["فيديوهات الباجز من أعلى محتوى شيرينج", "Clash Royale مجتمع كبير جداً"], challenges: ["باجز في التحديث الجديد", "باجز في الـ Tournament", "إزاي تستغل الباجز"] },
  { emoji: "💪", genre: "RPG", title: "بنيت أقوى شخصية في Diablo Immortal مجاناً!", description: "شرح كامل إزاي تبني شخصية قوية جداً في Diablo Immortal من غير ما تدفع أي فلوس!", why: "محتوى الـ F2P Guide من أعلى محتوى طلباً", reason: "معظم اللاعبين مش عايزين يدفعوا وبيدوروا على بدايل", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Diablo Immortal من أكتر الألعاب الموبايل", "محتوى F2P دايماً في الطلب الضخم"], challenges: ["أفضل Class مجاني", "إزاي تجمع Resources بسرعة", "أفضل Build بدون Pay"] },
  { emoji: "🎭", genre: "Mobile", title: "لعبت Among Us مع غرباء واكتشفت دراما جامدة!", description: "سيشن Among Us مع غرباء على النت وحصلت مواقف درامية ومضحكة ومثيرة جداً!", why: "Among Us محتوى ترفيهي واجتماعي عالي التفاعل", reason: "الناس بتحب تتفرج على المواقف الاجتماعية الغريبة والمضحكة", successRate: 82, successLabel: "جيد ✅", successType: "good", proof: ["Among Us لسه مجتمعه كبير", "محتوى السوشيال جيمنج من أعلى محتوى"], challenges: ["لعب Impostor بس", "تحدي الكذب المثالي", "فوز بدون ما تقتل حد"] },
  { emoji: "⚡", genre: "Battle Royale", title: "أسرع Chicken Dinner في PUBG تاريخي!", description: "تحدي الفوز بأسرع وقت ممكن في PUBG، مع شرح الاستراتيجية الجنونية اللي استخدمتها!", why: "تحديات السرعة من أعلى تحديات الجيمنج", reason: "الناس بتتحداها وبتحاول تكسر الرقم القياسي", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Speed Run challenges من أعلى محتوى", "التعليقات على التحديات دي دايماً ضخمة"], challenges: ["أسرع Win في Fortnite", "Speed Run في Warzone", "أسرع Rank Up"] },
  { emoji: "🌈", genre: "Mobile", title: "كيف تكسب من الجيمنج في مصر والسعودية 2025!", description: "شرح عملي وواقعي لطرق الكسب من الجيمنج في العالم العربي، من التريم لـ Esports لليوتيوب!", why: "محتوى الكسب من الجيمنج من أعلى محتوى بحثاً", reason: "كل شاب في العالم العربي بيحلم يكسب من الجيمنج", successRate: 93, successLabel: "نار 🔥", successType: "hot", proof: ["من أكتر الكلمات بحثاً في الجيمنج العربي", "التفاعل على المحتوى ده ضخم جداً"], challenges: ["Streaming على تويتش", "Esports المحترف", "يوتيوب والمونتاج"] },
  { emoji: "🎯", genre: "FPS", title: "أفضل Crosshair في Valorant للـ Headshots!", description: "مقارنة بين أفضل 5 Crosshairs في Valorant وإيه الفرق في دقة التصويب والـ Headshots.", why: "محتوى الـ Settings والـ Setup من أعلى محتوى", reason: "كل لاعب Valorant عايز يحسن Aim وبيدور على الـ Crosshair المثالي", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["Best Crosshair Valorant من أعلى كلمات السيرش", "مجتمع Valorant ضخم جداً"], challenges: ["Crosshair اللاعبين المحترفين", "Crosshair للـ Snipers", "Crosshair للمبتدئين"] },
  { emoji: "😱", genre: "Horror", title: "أترندي أكتر لعبة رعب في 2025!", description: "مراجعة وتجربة أترندي لعبة رعب جديدة في 2025 مع ردود فعل حقيقية وغير متوقعة!", why: "ألعاب الرعب دايماً في القمة من ناحية المشاهدات", reason: "الجمهور بيحب يتفرج على ردود الفعل الحقيقية للرعب", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["Horror Games Reaction من أعلى محتوى يوتيوب", "تيك توك مليان محتوى رعب جيمنج"], challenges: ["لعب من غير صوت", "لعب في الظلام الكامل", "تحدي لعب لساعة متواصلة"] },
  { emoji: "🏆", genre: "Esports", title: "أسرار محترفي Esports مش حد بيعرفها!", description: "كشف 7 أسرار وروتين يومي للاعبين المحترفين في Esports إزاي بيتدربوا ويحافظوا على مستواهم.", why: "محتوى Esports والمحترفين من أعلى محتوى", reason: "الجمهور بيحب يتعلم من المحترفين ويعرف أسرارهم", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Esports Pro Secrets من أعلى كلمات البحث", "مجتمع Esports ينمو بسرعة في الشرق الأوسط"], challenges: ["روتين التدريب اليومي", "إزاي تتحكم في الـ Tilt", "أسرار الـ Mental Game"] },
  { emoji: "🎮", genre: "Mobile", title: "أعلى 10 لاعبين في العالم العربي في Free Fire!", description: "قائمة أقوى 10 لاعبين عرب في Free Fire مع تحليل لأسلوب لعب كل واحد ومميزاته.", why: "محتوى القوائم والتصنيفات من أعلى محتوى تفاعلاً", reason: "الناس دايماً فضولية تعرف مين الأفضل وبتتجادل في التعليقات", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Top Players Lists من أعلى فيديوهات الجيمنج", "التجادل في التعليقات بيزيد الـ Engagement"], challenges: ["Top 10 PUBG عرب", "Top 10 Valorant عرب", "Top 10 Mobile Legends عرب"] },
  { emoji: "💥", genre: "FPS", title: "استغليت باجز Warzone وفزت 10 مرات متتالية!", description: "اكتشاف باجز في Warzone واستغلالها للفوز بطريقة مثيرة، مع شرح كل باجز وإزاي تستخدمها!", why: "محتوى الباجز والـ Exploits دايماً فيروسي", reason: "الجمهور بيحب يتعلم الطرق الذكية والغير تقليدية", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Warzone Glitches من أعلى كلمات البحث", "فيديوهات الباجز بتتشير بشكل كبير"], challenges: ["باجز التخفي", "باجز الـ Map", "باجز الأسلحة"] },
  { emoji: "🌙", genre: "RPG", title: "لعبت 24 ساعة متواصلة في Elden Ring!", description: "تحدي 24 ساعة في Elden Ring بدون نوم، التحديات والمشاعر الحقيقية في رحلة ممتعة ومجنونة!", why: "تحديات الـ Marathon Gaming من أعلى محتوى متابعة", reason: "الجمهور بيتابع التحديات الطويلة ويشجع ويتفاعل", successRate: 91, successLabel: "نار 🔥", successType: "hot", proof: ["24 Hour Gaming Challenge من أعلى تحديات يوتيوب", "التفاعل على الـ Streams الطويلة ضخم"], challenges: ["24 ساعة في Dark Souls", "48 ساعة في Minecraft", "لعب بدون نوم لأسبوع"] },
  { emoji: "🎪", genre: "Mobile", title: "فضحت أكبر Cheaters في PUBG Mobile!", description: "كشف واجه Cheaters في PUBG Mobile بشكل مباشر وتسجيل ردود فعلهم وإزاي الشركة بتتعامل معاهم.", why: "محتوى كشف الغشاشين من أعلى محتوى تفاعلاً وغضباً", reason: "الجمهور بيكره الغش ويحب المحتوى اللي بيكشفه", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["Anti-Cheat Content من أعلى محتوى تفاعلاً", "التعليقات الغاضبة بتزيد الـ Engagement"], challenges: ["كشف Cheaters في Valorant", "مواجهة Hackers في CS2", "Report System فعلاً بيشتغل؟"] },
  { emoji: "🚀", genre: "FPS", title: "جربت أضعف سلاح في Apex Legends وفزت!", description: "تحدي استخدام أضعف سلاح في Apex Legends وحاولت أفوز بيه، والنتيجة كانت صادمة!", why: "تحديات الأسلحة الضعيفة من أعلى التحديات", reason: "الجمهور بيحب يشوف التحديات المستحيلة والنتايج المفاجئة", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Worst Weapon Challenge من أعلى تحديات Apex", "مجتمع Apex كبير ومتفاعل جداً"], challenges: ["أضعف سلاح في Valorant", "أضعف هيرو في MOBA", "أضعف Class في RPG"] },
  { emoji: "😂", genre: "Mobile", title: "لما الـ Ping وصل 999 وأنا في أهم ماتش!", description: "مواقف مضحكة ومؤلمة لما النت قطع في أحرج اللحظات، مع ردود الفعل الحقيقية!", why: "محتوى Ping ومشاكل النت من أعلى محتوى تعاطفاً", reason: "كل لاعب عنده تجربة مشابهة وبيتعاطف ويضحك", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["High Ping Moments من أعلى محتوى كوميدي في الجيمنج", "التعليقات على المحتوى ده ضخمة جداً"], challenges: ["لعب على 1000 Ping", "Lag Switch Trolling", "Offline Gaming Challenge"] },
  { emoji: "🏅", genre: "Battle Royale", title: "أفضل Landing Spots في Fortnite الموسم الجديد!", description: "تحليل أفضل 5 أماكن نزول في Fortnite الموسم الجديد مع شرح إزاي تبدأ قوي وتجمع لوت بسرعة.", why: "محتوى الموسم الجديد دايماً في التريند مباشرة", reason: "كل لاعب بيدور على أفضل استراتيجية في البداية", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["Best Landing Spots من أعلى كلمات البحث بعد كل موسم", "Fortnite مجتمعه ضخم جداً"], challenges: ["أسوأ Landing Spots", "Landing في أصعب مكان", "Landing بدون سلاح"] },
  { emoji: "⚔️", genre: "MOBA", title: "أسرار الـ Jungling في League of Legends!", description: "شرح شامل لأسرار دور الـ Jungler في League of Legends وإزاي تتحكم في الـ Map وتساعد فريقك.", why: "Jungle guide من أعلى محتوى مطلوب في LoL", reason: "الـ Jungle من أصعب الأدوار وكل لاعب عايز يفهمه", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["LoL Jungle Guide من أعلى كلمات البحث", "مجتمع League of Legends ضخم جداً"], challenges: ["Jungle بدون Smite", "Invade الـ Enemy Jungle", "Jungle في أقل من 3 دقايق"] },
  { emoji: "🎯", genre: "Mobile", title: "تحدي الـ Headshot فقط في Free Fire!", description: "تحدي لعب Free Fire بالـ Headshot بس، كل kill لازم تكون Headshot وإلا الماتش ماعدش!", why: "Headshot Challenges من أعلى تحديات المحتوى", reason: "الجمهور بيحب يشوف التحديات الصعبة والمهارة العالية", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Headshot Only Challenge فيروسي جداً", "Free Fire مجتمعه ضخم في الشرق الأوسط"], challenges: ["Headshot بأضعف سلاح", "Headshot من مسافة بعيدة", "Headshot بدون scope"] },
  { emoji: "🌟", genre: "RPG", title: "أفضل 5 ألعاب RPG موبايل في 2025 مجاناً!", description: "قائمة أفضل 5 ألعاب RPG على الموبايل في 2025 مجانية وتستحق الوقت والتجربة.", why: "قوائم أفضل الألعاب من أعلى محتوى بحثاً", reason: "الناس دايماً بتدور على ألعاب جديدة تلعبها", successRate: 84, successLabel: "جيد ✅", successType: "good", proof: ["Best Mobile RPG 2025 من أعلى كلمات البحث", "قوائم الألعاب بتجيب مشاهدات ضخمة"], challenges: ["أفضل ألعاب Offline", "أفضل ألعاب للمبتدئين", "أفضل ألعاب بدون نت"] },
  { emoji: "💀", genre: "FPS", title: "لعبت Dark Souls للمرة الأولى وبكيت!", description: "تجربة أول مرة في Dark Souls، الفشل المتكرر والإصرار والانتصار النهائي في رحلة عاطفية مؤثرة!", why: "Dark Souls First Timer من أعلى محتوى", reason: "الجمهور بيتعاطف ويتشجع ويتفاعل مع رحلة التعلم", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["Dark Souls Reaction من أعلى محتوى يوتيوب", "مجتمع Souls Games كبير ومتفاعل"], challenges: ["Dark Souls بدون تلتش", "Dark Souls Speed Run", "Dark Souls بأضعف Build"] },
  { emoji: "😤", genre: "MOBA", title: "أسوأ Teammates في Mobile Legends وإزاي تفوز رغمهم!", description: "تجربة لعب مع أسوأ فريق ممكن في Mobile Legends وإزاي ممكن تفوز بالمهارة والاستراتيجية الصح.", why: "Bad Teammates محتوى من أعلى محتوى تفاعلاً", reason: "كل لاعب عنده تجربة مشابهة وبيتعاطف ويشارك", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Bad Teammates Moments من أعلى محتوى", "التعليقات على المحتوى ده ضخمة"], challenges: ["فوز مع أضعف فريق", "Carry الفريق كله لوحدك", "فوز من غير ما تتكلم مع الفريق"] },
  { emoji: "🎮", genre: "General", title: "إزاي تبدأ قناة جيمنج ناجحة في 2025!", description: "دليل عملي شامل لبدء قناة جيمنج ناجحة في 2025 من الصفر، الأدوات والاستراتيجيات والأخطاء.", why: "محتوى كيف تبدأ قناة يوتيوب من أعلى محتوى بحثاً", reason: "ملايين شاب بيحلم ببدء قناة جيمنج ناجحة", successRate: 92, successLabel: "نار 🔥", successType: "hot", proof: ["How to Start Gaming Channel من أعلى كلمات البحث", "المحتوى ده بيجيب مشتركين جدد كتير"], challenges: ["بدء قناة بدون معدات", "أول 1000 مشترك", "المونتاج المحترف مجاناً"] },
  { emoji: "🔥", genre: "Battle Royale", title: "تحدي الـ Sniper Only في Warzone!", description: "تحدي الفوز في Warzone بالـ Sniper بس، كل kill لازم تكون من مسافة بعيدة بالـ Sniper!", why: "Sniper Only Challenge من أعلى تحديات الجيمنج", reason: "الجمهور بيحب يشوف المهارة العالية في الـ Sniping", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Sniper Only Warzone فيروسي جداً", "Sniping Content من أعلى محتوى FPS"], challenges: ["Sniper بمسافة 1 كم", "Quick Scope Only", "Sniper بدون Scope"] },
  { emoji: "⚡", genre: "Mobile", title: "أسرع طريقة تجمع Diamonds في Mobile Legends مجاناً!", description: "شرح 5 طرق قانونية ومضمونة لجمع الـ Diamonds في Mobile Legends من غير ما تدفع فلوس.", why: "Free Diamonds Guide من أعلى محتوى مطلوب", reason: "كل لاعب عايز الـ Diamonds مجاناً وبيدور على طرق", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["Free Diamonds ML من أعلى كلمات البحث", "المحتوى ده بيجيب مشاهدات ضخمة جداً"], challenges: ["Free Skins بدون Diamonds", "أسرع طريقة تجمع Resources", "F2P Complete Guide"] },
  { emoji: "🎭", genre: "General", title: "أغرب 10 لحظات في تاريخ الجيمنج!", description: "تجميع أغرب وأطرف 10 لحظات حصلت في عالم الجيمنج، من البطولات للـ Streaming للألعاب نفسها.", why: "Compilation Videos من أعلى محتوى مشاهدة", reason: "الناس بتحب تشوف المحتوى الممتع والغير متوقع", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Gaming Moments Compilation فيروسي دايماً", "المحتوى التجميعي بيتشير بشكل كبير"], challenges: ["أغرب لحظات في Esports", "أطرف باجز في الألعاب", "أصعب لحظات في الجيمنج"] },
  { emoji: "🏆", genre: "Esports", title: "حضرت بطولة Esports وشفت ده!", description: "تقرير من داخل بطولة Esports عربية مع مقابلات اللاعبين وأجواء الحدث والكواليس!", why: "محتوى Esports Events من أعلى محتوى", reason: "الجمهور بيحب يشوف ما وراء الكواليس", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["Esports Event Coverage من أعلى محتوى", "مجتمع Esports في العالم العربي ينمو بسرعة"], challenges: ["مقابلات اللاعبين المحترفين", "كواليس البطولة", "تحليل المباريات"] },
  { emoji: "💥", genre: "FPS", title: "أقوى 5 Plays في تاريخ CS2!", description: "تجميع أقوى 5 لحظات وـ Plays في تاريخ CS2، مع تحليل إيه اللي خلاها أسطورية.", why: "Best Plays Compilation من أعلى محتوى CS2", reason: "مجتمع CS2 ضخم جداً وبيتفاعل مع المحتوى الكلاسيكي", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Best CS2 Plays من أعلى كلمات البحث", "المحتوى الكلاسيكي في CS دايماً بيتشير"], challenges: ["أقوى Clutch في CS2", "أصعب Shot في التاريخ", "أغرب Win Condition"] },
  { emoji: "🌈", genre: "Mobile", title: "ليه تلعب Genshin Impact في 2025؟", description: "شرح مقنع وصادق ليه Genshin Impact لسه يستحق اللعب في 2025 رغم وجود ألعاب جديدة.", why: "Is Genshin Worth It 2025 من أعلى كلمات البحث", reason: "مجتمع Genshin ضخم وكل تحديث بيجيب لاعبين جدد", successRate: 84, successLabel: "جيد ✅", successType: "good", proof: ["Genshin Impact Review 2025 من أعلى كلمات البحث", "اللعبة لسه من أعلى الألعاب إيرادات"], challenges: ["شرح Genshin للمبتدئين", "Genshin F2P Guide 2025", "أفضل شخصيات Genshin 2025"] },
  { emoji: "😱", genre: "Battle Royale", title: "فوزت بـ Fortnite بالـ Pickaxe بس!", description: "تحدي الفوز في Fortnite باستخدام الـ Pickaxe بس بدون أسلحة، والنتيجة كانت مجنونة!", why: "Pickaxe Only Challenge من أعلى تحديات Fortnite", reason: "الجمهور بيحب التحديات المستحيلة والمضحكة", successRate: 91, successLabel: "نار 🔥", successType: "hot", proof: ["Pickaxe Only Win فيروسي جداً في Fortnite", "التحديات المستحيلة دايماً بتفجر"], challenges: ["فوز بدون أسلحة", "فوز بدون بناء وبدون أسلحة", "فوز بأضعف Loadout"] },
  { emoji: "⚔️", genre: "RPG", title: "أفضل Build في Baldur Gate 3 للمبتدئين!", description: "شرح مبسط لأفضل Build للمبتدئين في Baldur Gate 3 عشان تستمتع باللعبة من أول لعبة.", why: "Baldur Gate 3 Build Guide من أعلى كلمات البحث", reason: "اللعبة من أفضل ألعاب 2024 ومجتمعها ضخم جداً", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["BG3 Best Build من أعلى كلمات البحث", "Baldur Gate 3 مجتمعه من أكبر مجتمعات RPG"], challenges: ["أصعب Build في BG3", "Solo Run في BG3", "BG3 بدون Magic"] },
  { emoji: "🎮", genre: "General", title: "أفضل هيدست جيمنج تحت 500 جنيه!", description: "مراجعة صادقة وعملية لأفضل هيدست جيمنج بسعر مناسب في مصر والسعودية في 2025.", why: "محتوى المراجعات والمنتجات من أعلى محتوى عربي", reason: "الناس دايماً بتدور على أفضل منتج بأقل سعر", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["أفضل هيدست جيمنج من أعلى كلمات البحث العربي", "مراجعات المنتجات بتجيب مشاهدات ضخمة"], challenges: ["أفضل ماوس جيمنج رخيص", "أفضل شاشة جيمنج", "أفضل كيبورد للجيمنج"] },
  { emoji: "💪", genre: "FPS", title: "تدريب الـ Aim لمدة 30 يوم والنتيجة!", description: "تجربة تدريب منظم على الـ Aim لمدة 30 يوم ورؤية التحسن الحقيقي والملموس.", why: "Aim Training Challenge من أعلى محتوى FPS", reason: "كل لاعب FPS عايز يحسن Aim وبيتابع التجارب دي", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["30 Day Aim Training من أعلى تحديات الجيمنج", "قبل وبعد التدريب بيجيب تفاعل ضخم"], challenges: ["60 يوم Aim Training", "Aim Training مع Pro Coach", "من أسوأ Aim لـ Radiant"] },
  { emoji: "🎯", genre: "Mobile", title: "أفضل Settings للـ Sensitivity في PUBG Mobile!", description: "شرح تفصيلي لأفضل إعدادات الـ Sensitivity في PUBG Mobile لكل أنواع اللعب والأجهزة.", why: "Best Sensitivity PUBG Mobile من أعلى كلمات البحث", reason: "كل لاعب PUBG Mobile بيدور على الـ Sensitivity المثالية", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["PUBG Mobile Sensitivity Guide من أعلى محتوى", "من أكتر الأسئلة في مجتمع PUBG Mobile"], challenges: ["Sensitivity للـ Gyroscope", "Sensitivity على جهاز ضعيف", "Sensitivity المحترفين"] },
  { emoji: "🌙", genre: "General", title: "Stream لمدة 12 ساعة وده اللي حصل!", description: "تجربة Stream طويل لمدة 12 ساعة متواصلة، التعب والمواقف المضحكة والتفاعل مع الجمهور.", why: "Marathon Stream من أعلى محتوى", reason: "الجمهور بيتفاعل مع الـ Streams الطويلة ويشجع", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Marathon Stream من أعلى تحديات الـ Streaming", "الـ Streams الطويلة بتبني Community أقوى"], challenges: ["24 Hour Stream", "Stream بدون توقف لأسبوع", "Stream مع متابعين بس"] },
  { emoji: "😂", genre: "Mobile", title: "لما جربت كل الشخصيات في Brawl Stars!", description: "تجربة مضحكة لعب بكل الشخصيات في Brawl Stars وإيه أغرب وأضعف وأقوى شخصية!", why: "All Characters Challenge من أعلى تحديات Brawl Stars", reason: "مجتمع Brawl Stars شباب صغير وبيتفاعل بشكل ضخم", successRate: 84, successLabel: "جيد ✅", successType: "good", proof: ["Brawl Stars All Characters من أعلى محتوى", "مجتمع Brawl Stars ضخم وشبابي"], challenges: ["أضعف شخصية في Brawl Stars", "فوز بكل الشخصيات", "Rank Up بأصعب شخصية"] },
  { emoji: "🔥", genre: "FPS", title: "كيف تسيطر على الـ Recoil في كل سلاح في Warzone!", description: "شرح مفصل لكيفية التحكم في الـ Recoil لكل سلاح في Warzone مع تمارين عملية.", why: "Recoil Control Guide من أعلى محتوى FPS", reason: "الـ Recoil من أصعب حاجات في الـ FPS وكل لاعب عايز يتعلمها", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Warzone Recoil Control من أعلى كلمات البحث", "محتوى التعلم والتحسين دايماً في الطلب"], challenges: ["Recoil Control في CS2", "No Recoil Build في PUBG", "Spray Pattern Training"] },
  { emoji: "⚡", genre: "Battle Royale", title: "أسرار الـ Zone في PUBG مش حد بيعرفها!", description: "شرح أسرار وخفايا الـ Zone في PUBG، إزاي تستخدمها لصالحك وتفوز بطريقة ذكية.", why: "Zone Strategy PUBG من أعلى محتوى استراتيجي", reason: "الـ Zone من أهم عناصر PUBG وكل لاعب عايز يفهمها", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["PUBG Zone Tips من أعلى كلمات البحث", "الاستراتيجيات المخفية بتجيب مشاهدات ضخمة"], challenges: ["فوز من داخل الـ Zone", "Zone Edge Strategy", "Final Zone Positioning"] },
  { emoji: "🏅", genre: "MOBA", title: "من الـ Bronze لـ Grand Master في 2 أسبوع!", description: "رحلة حقيقية من أضعف رانك لأعلى رانك في Mobile Legends خلال أسبوعين بس مع شرح كل خطوة.", why: "رحلات الـ Rank Up من أعلى محتوى MOBA", reason: "الناس بتتابع الرحلات وبتتعلم وبتتحفز", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["ML Rank Up Journey من أعلى محتوى Mobile Legends", "التفاعل على الـ Progress Content ضخم"], challenges: ["Rank Up بهيرو واحد", "Rank Up بدون ما تخسر", "Rank Up في أقل وقت"] },
  { emoji: "🎭", genre: "General", title: "تحديت أفضل لاعب في المنطقة وده اللي حصل!", description: "قبول تحدي من أفضل لاعب في المنطقة، التحضير والمباراة والنتيجة الصادمة!", why: "Player vs Player Challenges من أعلى محتوى", reason: "الجمهور بيحب يشوف المنافسات الحقيقية والدراما", successRate: 92, successLabel: "نار 🔥", successType: "hot", proof: ["1v1 Challenge من أعلى محتوى تفاعلاً", "التحديات الشخصية بتجيب دراما وتفاعل ضخم"], challenges: ["تحدي أفضل لاعب في مصر", "تحدي Pro Player", "تحدي المشترك الـ 10000"] },
  { emoji: "💥", genre: "RPG", title: "أعلى Damage في تاريخ Genshin Impact!", description: "بناء شخصية بأعلى Damage ممكن في Genshin Impact وتحقيق أرقام مجنونة ومش مصدقة!", why: "Max Damage Build من أعلى محتوى Genshin", reason: "الجمهور بيحب يشوف الأرقام المجنونة والـ Builds المتطرفة", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Genshin Max Damage من أعلى كلمات البحث", "مجتمع Genshin بيتفاعل مع الـ Builds الضخمة"], challenges: ["أعلى Damage في الألعاب", "One Shot Build", "أقوى Character في الجيمنج"] },
  { emoji: "🎮", genre: "Mobile", title: "مراجعة أحدث لعبة جيمنج عربية في 2025!", description: "مراجعة صادقة ومفصلة لأحدث لعبة جيمنج عربية الصنع في 2025 مع مقارنة بالألعاب العالمية.", why: "محتوى الألعاب العربية من أعلى محتوى قومي وتفاعلاً", reason: "الجمهور العربي فخور بالمنتجات العربية وبيدعمها", successRate: 83, successLabel: "جيد ✅", successType: "good", proof: ["Arab Games Review من أعلى محتوى في المنطقة", "التفاعل القومي على المحتوى العربي ضخم"], challenges: ["مقارنة الألعاب العربية والعالمية", "دعم صناع الألعاب العرب", "تطوير الجيمنج العربي"] },
  { emoji: "🌟", genre: "FPS", title: "أفضل 3 Agents في Valorant للـ Ranked 2025!", description: "تحليل أفضل 3 Agents في Valorant لـ Ranked Play في 2025 وليه هم الأفضل مع شرح مبسط.", why: "Best Agents Valorant 2025 من أعلى كلمات البحث", reason: "مجتمع Valorant ضخم وبيدور على أفضل Agents للـ Ranked", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["Valorant Best Agents من أعلى محتوى مطلوب", "Valorant مجتمعه من أكبر مجتمعات FPS"], challenges: ["Best Agents للمبتدئين", "Agents للـ Solo Queue", "Agents للـ Team Play"] },
  { emoji: "😤", genre: "Battle Royale", title: "تحديت نفسي بـ 100 Win في أسبوع!", description: "تحدي تحقيق 100 Win في PUBG Mobile خلال أسبوع واحد، التعب والإصرار والنتيجة النهائية!", why: "100 Win Challenge من أعلى تحديات الجيمنج", reason: "التحديات الصعبة بتجيب متابعة مستمرة وتفاعل ضخم", successRate: 91, successLabel: "نار 🔥", successType: "hot", proof: ["100 Win Challenge فيروسي في جيمنج يوتيوب", "التحديات الطموحة بتبني قاعدة جماهيرية قوية"], challenges: ["100 Kill في يوم", "Win 50 مرة متتالية", "1000 ساعة جيمنج"] },
  { emoji: "🔫", genre: "FPS", title: "أفضل Loadout في Warzone بعد التحديث الجديد!", description: "شرح أفضل Loadout في Warzone بعد آخر تحديث مع مقارنة الأسلحة والـ Attachments المثالية.", why: "Best Loadout After Update من أعلى كلمات البحث", reason: "كل تحديث بيغير المحتوى وكل لاعب بيدور على أفضل Loadout", successRate: 90, successLabel: "نار 🔥", successType: "hot", proof: ["Warzone Best Loadout من أعلى كلمات البحث دايماً", "المحتوى بعد التحديثات بيجيب مشاهدات ضخمة فوراً"], challenges: ["Loadout بعد كل Nerf", "أرخص Loadout فعال", "Loadout المحترفين"] },
  { emoji: "🎯", genre: "MOBA", title: "إزاي تكسب من Esports العربي في 2025!", description: "دليل شامل لكيفية دخول عالم Esports العربي والكسب منه، الفرق المتاحة والبطولات والرواتب.", why: "Esports Career Guide من أعلى محتوى بحثاً في العالم العربي", reason: "ملايين شاب في العالم العربي يحلم بمهنة في Esports", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Arab Esports Career من أعلى كلمات البحث", "الـ Esports في العالم العربي ينمو بشكل ضخم"], challenges: ["أول خطوة في Esports", "إزاي تنضم لفريق Esports", "الرواتب في Esports العربي"] },
  { emoji: "💀", genre: "Battle Royale", title: "أصعب 5 لحظات في حياتي كلاعب!", description: "مشاركة أصعب وأحرج 5 لحظات حصلت معي كلاعب، من الخسارات الكبيرة للمواقف المحرجة.", why: "Personal Gaming Stories من أعلى محتوى تفاعلاً", reason: "الجمهور بيحب المحتوى الشخصي والصادق والمشاعر الحقيقية", successRate: 86, successLabel: "نار 🔥", successType: "hot", proof: ["Gaming Fails Compilation من أعلى محتوى", "المحتوى الشخصي بيبني علاقة أقوى مع الجمهور"], challenges: ["أخجل لحظاتي في الجيمنج", "أكبر خسارة في حياتي", "لحظة كادت تخليني أوقف الجيمنج"] },
  { emoji: "⚡", genre: "Mobile", title: "ليه كل الناس بتلعب Clash of Clans في 2025؟", description: "شرح سر الجاذبية المستمرة لـ Clash of Clans ولماذا لسه من أعلى الألعاب في 2025.", why: "Why Still Play Clash of Clans من أعلى كلمات البحث", reason: "Clash of Clans من أطول الألعاب عمراً وجمهورها ضخم", successRate: 84, successLabel: "جيد ✅", successType: "good", proof: ["CoC Review 2025 من أعلى كلمات البحث", "اللعبة لسه في قمة الإيرادات عالمياً"], challenges: ["Base Design Clash of Clans", "Max Base بدون Pay", "أقوى Attack Strategy"] },
  { emoji: "🎮", genre: "General", title: "جربت Gaming Chair بـ 3000 جنيه وده رأيي!", description: "مراجعة صادقة وعملية لـ Gaming Chair بسعر متوسط، هل تستحق أم لأ؟", why: "Gaming Chair Review من أعلى محتوى مراجعات", reason: "كثير من اللاعبين بيدوروا على Gaming Chair مناسبة بسعر معقول", successRate: 85, successLabel: "نار 🔥", successType: "hot", proof: ["Gaming Chair Review من أعلى كلمات البحث العربي", "مراجعات المعدات بتجيب مشاهدات ضخمة"], challenges: ["أفضل Gaming Chair بأقل سعر", "هل Gaming Chair ضرورية؟", "Gaming Chair vs كرسي عادي"] },
  { emoji: "🌙", genre: "RPG", title: "أنهيت Zelda Tears of the Kingdom 100%!", description: "رحلة إنهاء Zelda Tears of the Kingdom بنسبة 100% مع كشف كل الأسرار والمناطق المخفية.", why: "100% Completion من أعلى تحديات ألعاب RPG", reason: "مجتمع Zelda ضخم جداً ومتحمس للمحتوى الشامل", successRate: 87, successLabel: "نار 🔥", successType: "hot", proof: ["Zelda TotK 100% من أعلى كلمات البحث", "مجتمع Zelda من أقوى مجتمعات الجيمنج"], challenges: ["100% في Dark Souls", "All Secrets في Elden Ring", "Speedrun مع 100%"] },
  { emoji: "😂", genre: "FPS", title: "لعبت Valorant بعيون مغمضة وده اللي حصل!", description: "تحدي مضحك لعب Valorant بعيون مغمضة بالكامل، كيف كان الـ Gameplay وما هي النتيجة المجنونة!", why: "Blind Gaming Challenge من أعلى تحديات الكوميديا", reason: "التحديات المستحيلة الكوميدية بتجيب ضحك وتفاعل ضخم", successRate: 89, successLabel: "نار 🔥", successType: "hot", proof: ["Blind Gaming Challenge فيروسي جداً", "الجمهور بيحب التحديات المضحكة والمستحيلة"], challenges: ["PUBG بعيون مغمضة", "FIFA بعيون مغمضة", "Racing Games بعيون مغمضة"] },
  { emoji: "🏆", genre: "General", title: "أعلى 10 ألعاب في العالم العربي 2025!", description: "قائمة أعلى 10 ألعاب لعبها العرب في 2025 بناءً على الإحصاءات والأرقام الحقيقية.", why: "Top Games Arab World من أعلى محتوى إحصائي", reason: "الناس بتحب تعرف إيه أكتر الألعاب انتشاراً في منطقتهم", successRate: 88, successLabel: "نار 🔥", successType: "hot", proof: ["Most Played Games Arab World من أعلى كلمات البحث", "المحتوى الإحصائي بيجيب نقاشات ضخمة"], challenges: ["أعلى ألعاب في مصر", "أعلى ألعاب في السعودية", "أعلى ألعاب في الخليج"] }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { platform, genre } = req.body || {};

  let filtered = [...IDEAS];

  // Filter by genre if specified
  if (genre) {
    const genreMap = {
      'fps': 'FPS',
      'moba': 'MOBA',
      'battle royale': 'Battle Royale',
      'rpg': 'RPG',
      'mobile': 'Mobile'
    };
    const mappedGenre = genreMap[genre.toLowerCase()];
    if (mappedGenre) {
      const genreFiltered = filtered.filter(i => i.genre === mappedGenre || i.genre === 'General');
      if (genreFiltered.length >= 3) filtered = genreFiltered;
    }
  }

  // Shuffle and pick 3
  const shuffled = filtered.sort(() => Math.random() - 0.5);
  const ideas = shuffled.slice(0, 3);

  return res.status(200).json({ ideas });
}
